export const RENDERING_CONSTANTS = {
  // Grid
  GRID_LIGHT_COLOR: 'rgba(0,0,0,0.05)',
  GRID_DARK_COLOR: 'rgba(255,255,255,0.05)',
  GRID_LINE_WIDTH: 1,

  // Theme colors
  THEME_LIGHT_BG: '#f8fafc',
  THEME_DARK_BG: '#131316',

  // Welcome screen
  WELCOME_LIGHT_TEXT: '#0f172a',
  WELCOME_DARK_TEXT: '#cbd5e0',
  WELCOME_LIGHT_SUBTEXT: 'rgba(15, 23, 42, 0.6)',
  WELCOME_DARK_SUBTEXT: 'rgba(203, 213, 224, 0.6)',
  WELCOME_FONT_SIZE: 42,
  WELCOME_SUB_FONT_SIZE: 20,
  WELCOME_FONT_FAMILY: "'Architects Daughter', cursive",

  // Binding hover
  BINDING_HOVER_COLOR: '#60a5fa',
  BINDING_HOVER_LINE_WIDTH: 1.5,
  BINDING_HOVER_ALPHA: 0.7,
  BINDING_HOVER_PADDING: 4,

  // Erasing path
  ERASING_PATH_COLOR: 'rgba(139, 147, 158,',
  ERASING_PATH_LINE_WIDTH: 4,
  ERASING_PATH_ALPHA_BASE: 0.8,

  // Selection box
  SELECTION_BOX_FILL: 'rgba(96, 165, 250, 0.08)',
  SELECTION_BOX_STROKE: 'rgba(59, 130, 246, 0.6)',
  SELECTION_BOX_LINE_WIDTH: 1,

  // Snap lines
  SNAP_LINE_COLOR: '#f87171',
  SNAP_LINE_DASH: 4,

  // Text rendering
  TEXT_DEFAULT_FONT_SIZE: 20,
  TEXT_DEFAULT_FONT_FAMILY: "'Architects Daughter', cursive",
  TEXT_LINE_HEIGHT_RATIO: 1.2,
  TEXT_MIN_FONT_SIZE: 8,
  TEXT_DEFAULT_PADDING: 8,
  TEXT_CONNECTOR_PADDING: 4,
  TEXT_CLIP_PADDING: 2,

  // Shape rendering
  SHAPE_DEFAULT_OPACITY: 1,
  SHAPE_ERASING_OPACITY_MULTIPLIER: 0.3,

  // Selection frame
  SELECTION_FRAME_COLOR: '#60a5fa',
  SELECTION_HANDLE_STROKE: '#3b82f6',
  SELECTION_FRAME_LINE_WIDTH: 1,
  SELECTION_FRAME_ALPHA: 0.85,
  SELECTION_HANDLE_CORNER_RADIUS: 5,
  SELECTION_HANDLE_MIDPOINT_RADIUS: 4,
  SELECTION_HANDLE_LINE_WIDTH: 1.8,
  SELECTION_HANDLE_MID_LINE_WIDTH: 1.5,
  SELECTION_HANDLE_SHADOW_COLOR: 'rgba(59,130,246,0.25)',
  SELECTION_HANDLE_SHADOW_BLUR: 5,

  // Lock icon
  LOCK_ICON_OFFSET: 6,

  // Connection points
  CONNECTION_POINT_SIZE: 5,
  CONNECTION_POINT_ACTIVE_SIZE: 8,
  CONNECTION_POINT_LINE_WIDTH: 1.2,
} as const;
